CUSTOM_CLASSES = []
CLASSES_GOAL1 = [
    "person",
    "clothing",
    "shoes",
    "hat",
    "glasses",
    "watch",
    "bag",
    "jewelry",
    "mask"
]

CLASSES_GOAL2 = [
    "plate",
    "cup",
    "mug",
    "bowl",
    "fork",
    "knife",
    "spoon",
    "napkin",
    "glass",
    "bottle",
    "book",
    "laptop",
    "phone",
    "pen",
    "pencil",
    "notebook",
    "tablet",
    "keyboard",
    "mouse",
    "remote",
    "keys",
    "wallet",
    "watch",
    "food",
    "fruit",
    "snacks",
    "lamp",
    "vase",
    "flower",
    "paper"
]

CLASSES_GOAL3 = [
    "shirt",
    "t-shirt",
    "blouse",
    "sweater",
    "jacket",
    "coat",
    "dress",
    "skirt",
    "jeans",
    "pants",
    "shorts",
    "suit",
    "tie",
    "scarf",
    "hat",
    "gloves",
    "socks",
    "shoes",
    "boots",
    "sneakers",
    "belt",
    "watch",
    "glasses",
    "earrings",
    "necklace",
    "bracelet",
    "ring",
    "bag",
    "backpack",
    "umbrella"
]


CLASSES_GOAL4 = [
    "laptop",
    "computer",
    "keyboard",
    "mouse",
    "charger",
    "USB cable",
    "monitor",
    "desk",
    "table",
    "power adapter",
    "headphones",
    "tablet",
    "notebook",
    "pen",
    "phone",
    "coffee cup",
    "bottle"
    ]

CLASSES_GOAL5 = [
    'laptop',
    'desk',
    'mouse',
    'keyboard',
    'monitor',
    'telephone',
    'chair',
    'pen',
    'paper',
    'person'
    'printer',
    'poster',
    'backpack',
    'calculator',
    'stapler',
    'clock',
    'headphones',
    'paperclip',
    'printer paper',
    'bottle',
    'whiteboard',
    'marker',
    'trash can',
    'cabinet',
    'drawer',
    'box',
    'cup',
    'glass',
    'mug',
    'cable organizer',
    'monitor stand'
    'backpack',
    'bag',
    'wallet',
    'charger',
    'socket',
]



CUSTOM_CLASSES_SPECIFIC = [
    'laptop',
    'desk',
    'mouse',
    'keyboard',
    'monitor',
    'telephone',
    'chair',
    'book',
    'pen',
    'paper',
    'person'
    'notebook',
    'printer',
    'file cabinet',
    'computer tower',
    'poster',
    'poster stand',
    'coffee cup',
    'spectacles',
    'mouse pad',
    'lamp',
    'document',
    'backpack',
    'calculator',
    'stapler',
    'clock',
    'headphones',
    'paperclip',
    'bottle',
    'marker',
    'cabinet',
    'drawer',
    'pencil box',
    'box',
    'cup',
    'glass',
    'mug',
    'cable organizer',
    'monitor stand'
    'backpack',
    'wallet',
    'charger',
    'socket',
]



OPENIMAGE_CLASSES = ['Accordion', 'Adhesive tape', 'Aircraft', 'Airplane', 'Alarm clock', 'Alpaca', 'Ambulance', 'Animal', 'Ant', 'Antelope', 'Apple', 'Armadillo', 'Artichoke', 'Auto part', 'Axe', 'Backpack', 'Bagel', 'Baked goods', 'Balance beam', 'Ball', 'Balloon', 'Banana', 'Band-aid', 'Banjo', 'Barge', 'Barrel', 'Baseball bat', 'Baseball glove', 'Bat (Animal)', 'Bathroom accessory', 'Bathroom cabinet', 'Bathtub', 'Beaker', 'Bear', 'Bed', 'Bee', 'Beehive', 'Beer', 'Beetle', 'Bell pepper', 'Belt', 'Bench', 'Bicycle', 'Bicycle helmet', 'Bicycle wheel', 'Bidet', 'Billboard', 'Billiard table', 'Binoculars', 'Bird', 'Blender', 'Blue jay', 'Boat', 'Bomb', 'Book', 'Bookcase', 'Boot', 'Bottle', 'Bottle opener', 'Bow and arrow', 'Bowl', 'Bowling equipment', 'Box', 'Boy', 'Brassiere', 'Bread', 'Briefcase', 'Broccoli', 'Bronze sculpture', 'Brown bear', 'Building', 'Bull', 'Burrito', 'Bus', 'Bust', 'Butterfly', 'Cabbage', 'Cabinetry', 'Cake', 'Cake stand', 'Calculator', 'Camel', 'Camera', 'Can opener', 'Canary', 'Candle', 'Candy', 'Cannon', 'Canoe', 'Cantaloupe', 'Car', 'Carnivore', 'Carrot', 'Cart', 'Cassette deck', 'Castle', 'Cat', 'Cat furniture', 'Caterpillar', 'Cattle', 'Ceiling fan', 'Cello', 'Centipede', 'Chainsaw', 'Chair', 'Cheese', 'Cheetah', 'Chest of drawers', 'Chicken', 'Chime', 'Chisel', 'Chopsticks', 'Christmas tree', 'Clock', 'Closet', 'Clothing', 'Coat', 'Cocktail', 'Cocktail shaker', 'Coconut', 'Coffee', 'Coffee cup', 'Coffee table', 'Coffeemaker', 'Coin', 'Common fig', 'Common sunflower', 'Computer keyboard', 'Computer monitor', 'Computer mouse', 'Container', 'Convenience store', 'Cookie', 'Cooking spray', 'Corded phone', 'Cosmetics', 'Couch', 'Countertop', 'Cowboy hat', 'Crab', 'Cream', 'Cricket ball', 'Crocodile', 'Croissant', 'Crown', 'Crutch', 'Cucumber', 'Cupboard', 'Curtain', 'Cutting board', 'Dagger', 'Dairy Product', 'Deer', 'Desk', 'Dessert', 'Diaper', 'Dice', 'Digital clock', 'Dinosaur', 'Dishwasher', 'Dog', 'Dog bed', 'Doll', 'Dolphin', 'Door', 'Door handle', 'Doughnut', 'Dragonfly', 'Drawer', 'Dress', 'Drill (Tool)', 'Drink', 'Drinking straw', 'Drum', 'Duck', 'Dumbbell', 'Eagle', 'Earrings', 'Egg (Food)', 'Elephant', 'Envelope', 'Eraser', 'Face powder', 'Facial tissue holder', 'Falcon', 'Fashion accessory', 'Fast food', 'Fax', 'Fedora', 'Filing cabinet', 'Fire hydrant', 'Fireplace', 'Fish', 'Flag', 'Flashlight', 'Flower', 'Flowerpot', 'Flute', 'Flying disc', 'Food', 'Food processor', 'Football', 'Football helmet', 'Footwear', 'Fork', 'Fountain', 'Fox', 'French fries', 'French horn', 'Frog', 'Fruit', 'Frying pan', 'Furniture', 'Garden Asparagus', 'Gas stove', 'Giraffe', 'Girl', 'Glasses', 'Glove', 'Goat', 'Goggles', 'Goldfish', 'Golf ball', 'Golf cart', 'Gondola', 'Goose', 'Grape', 'Grapefruit', 'Grinder', 'Guacamole', 'Guitar', 'Hair dryer', 'Hair spray', 'Hamburger', 'Hammer', 'Hamster', 'Hand dryer', 'Handbag', 'Handgun', 'Harbor seal', 'Harmonica', 'Harp', 'Harpsichord', 'Hat', 'Headphones', 'Heater', 'Hedgehog', 'Helicopter', 'Helmet', 'High heels', 'Hiking equipment', 'Hippopotamus', 'Home appliance', 'Honeycomb', 'Horizontal bar', 'Horse', 'Hot dog', 'House', 'Houseplant', 'Human arm', 'Human beard', 'Human body', 'Human ear', 'Human eye', 'Human face', 'Human foot', 'Human hair', 'Human hand', 'Human head', 'Human leg', 'Human mouth', 'Human nose', 'Humidifier', 'Ice cream', 'Indoor rower', 'Infant bed', 'Insect', 'Invertebrate', 'Ipod', 'Isopod', 'Jacket', 'Jacuzzi', 'Jaguar (Animal)', 'Jeans', 'Jellyfish', 'Jet ski', 'Jug', 'Juice', 'Kangaroo', 'Kettle', 'Kitchen & dining room table', 'Kitchen appliance', 'Kitchen knife', 'Kitchen utensil', 'Kitchenware', 'Kite', 'Knife', 'Koala', 'Ladder', 'Ladle', 'Ladybug', 'Lamp', 'Land vehicle', 'Lantern', 'Laptop', 'Lavender (Plant)', 'Lemon', 'Leopard', 'Light bulb', 'Light switch', 'Lighthouse', 'Lily', 'Limousine', 'Lion', 'Lipstick', 'Lizard', 'Lobster', 'Loveseat', 'Luggage and bags', 'Lynx', 'Magpie', 'Mammal', 'Man', 'Mango', 'Maple', 'Maracas', 'Marine invertebrates', 'Marine mammal', 'Measuring cup', 'Mechanical fan', 'Medical equipment', 'Microphone', 'Microwave oven', 'Milk', 'Miniskirt', 'Mirror', 'Missile', 'Mixer', 'Mixing bowl', 'Mobile phone', 'Monkey', 'Moths and butterflies', 'Motorcycle', 'Mouse', 'Muffin', 'Mug', 'Mule', 'Mushroom', 'Musical instrument', 'Musical keyboard', 'Nail (Construction)', 'Necklace', 'Nightstand', 'Oboe', 'Office building', 'Office supplies', 'Orange', 'Organ (Musical Instrument)', 'Ostrich', 'Otter', 'Oven', 'Owl', 'Oyster', 'Paddle', 'Palm tree', 'Pancake', 'Panda', 'Paper cutter', 'Paper towel', 'Parachute', 'Parking meter', 'Parrot', 'Pasta', 'Pastry', 'Peach', 'Pear', 'Pen', 'Pencil case', 'Pencil sharpener', 'Penguin', 'Perfume', 'Person', 'Personal care', 'Personal flotation device', 'Piano', 'Picnic basket', 'Picture frame', 'Pig', 'Pillow', 'Pineapple', 'Pitcher (Container)', 'Pizza', 'Pizza cutter', 'Plant', 'Plastic bag', 'Plate', 'Platter', 'Plumbing fixture', 'Polar bear', 'Pomegranate', 'Popcorn', 'Porch', 'Porcupine', 'Poster', 'Potato', 'Power plugs and sockets', 'Pressure cooker', 'Pretzel', 'Printer', 'Pumpkin', 'Punching bag', 'Rabbit', 'Raccoon', 'Racket', 'Radish', 'Ratchet (Device)', 'Raven', 'Rays and skates', 'Red panda', 'Refrigerator', 'Remote control', 'Reptile', 'Rhinoceros', 'Rifle', 'Ring binder', 'Rocket', 'Roller skates', 'Rose', 'Rugby ball', 'Ruler', 'Salad', 'Salt and pepper shakers', 'Sandal', 'Sandwich', 'Saucer', 'Saxophone', 'Scale', 'Scarf', 'Scissors', 'Scoreboard', 'Scorpion', 'Screwdriver', 'Sculpture', 'Sea lion', 'Sea turtle', 'Seafood', 'Seahorse', 'Seat belt', 'Segway', 'Serving tray', 'Sewing machine', 'Shark', 'Sheep', 'Shelf', 'Shellfish', 'Shirt', 'Shorts', 'Shotgun', 'Shower', 'Shrimp', 'Sink', 'Skateboard', 'Ski', 'Skirt', 'Skull', 'Skunk', 'Skyscraper', 'Slow cooker', 'Snack', 'Snail', 'Snake', 'Snowboard', 'Snowman', 'Snowmobile', 'Snowplow', 'Soap dispenser', 'Sock', 'Sofa bed', 'Sombrero', 'Sparrow', 'Spatula', 'Spice rack', 'Spider', 'Spoon', 'Sports equipment', 'Sports uniform', 'Squash (Plant)', 'Squid', 'Squirrel', 'Stairs', 'Stapler', 'Starfish', 'Stationary bicycle', 'Stethoscope', 'Stool', 'Stop sign', 'Strawberry', 'Street light', 'Stretcher', 'Studio couch', 'Submarine', 'Submarine sandwich', 'Suit', 'Suitcase', 'Sun hat', 'Sunglasses', 'Surfboard', 'Sushi', 'Swan', 'Swim cap', 'Swimming pool', 'Swimwear', 'Sword', 'Syringe', 'Table', 'Table tennis racket', 'Tablet computer', 'Tableware', 'Taco', 'Tank', 'Tap', 'Tart', 'Taxi', 'Tea', 'Teapot', 'Teddy bear', 'Telephone', 'Television', 'Tennis ball', 'Tennis racket', 'Tent', 'Tiara', 'Tick', 'Tie', 'Tiger', 'Tin can', 'Tire', 'Toaster', 'Toilet', 'Toilet paper', 'Tomato', 'Tool', 'Toothbrush', 'Torch', 'Tortoise', 'Towel', 'Tower', 'Toy', 'Traffic light', 'Traffic sign', 'Train', 'Training bench', 'Treadmill', 'Tree', 'Tree house', 'Tripod', 'Trombone', 'Trousers', 'Truck', 'Trumpet', 'Turkey', 'Turtle', 'Umbrella', 'Unicycle', 'Van', 'Vase', 'Vegetable', 'Vehicle', 'Vehicle registration plate', 'Violin', 'Volleyball (Ball)', 'Waffle', 'Waffle iron', 'Wall clock', 'Wardrobe', 'Washing machine', 'Waste container', 'Watch', 'Watercraft', 'Watermelon', 'Weapon', 'Whale', 'Wheel', 'Wheelchair', 'Whisk', 'Whiteboard', 'Willow', 'Window', 'Window blind', 'Wine', 'Wine glass', 'Wine rack', 'Winter melon', 'Wok', 'Woman', 'Wood-burning stove', 'Woodpecker', 'Worm', 'Wrench', 'Zebra', 'Zucchini']  # Empty list to hold class names

VISUAL_CLASSES = ['spatial_relationship', 'color', 'shape', 'texture'] 

MANIPULATION_CLASSES = ['talk_less', 'pause', 'volume_high', 'volume_low', 'earcon']

SOUND_CLASSES = ["cow_moo", "acoustic_guitar", "person_running", "sea_waves", "tick_tock", "keyboard_musical", "fire_crackle", "beep", "raindrop", "playing_volleyball", "electric_piano", "coyote_howl", "chatter", "engine_accelerating_revving", "duck_quack", "snicker", "helicopter", "playing_table_tennis", "keys_jangling", "bird_squawk", "shofar", "snake_rattle", "cheering", "airplane", "crowd", "wind_noise_microphone", "chopping_food", "bicycle", "bassoon", "cough", "lion_roar", "whoosh_swoosh_swish", "snoring", "saxophone", "reverse_beeps", "foghorn", "telephone", "glass_breaking", "cat", "chicken_cluck", "skateboard", "skiing", "engine_starting", "guitar_tapping", "wind_rustling_leaves", "bus", "liquid_filling_container", "printer", "mechanical_fan", "piano", "rain", "electronic_organ", "rooster_crow", "tap", "bowling_impact", "giggling", "babble", "plucked_string_instrument", "air_horn", "percussion", "typewriter", "accordion", "click", "gasp", "liquid_pouring", "frying_food", "breathing", "bagpipes", "engine_knocking", "scuba_diving", "sink_filling_washing", "car_passing_by", "chopping_wood", "wind_instrument", "crying_sobbing", "power_windows", "smoke_detector", "rapping", "liquid_spraying", "telephone_bell_ringing", "motorcycle", "gargling", "applause", "cricket_chirp", "door", "silence", "singing", "playing_tennis", "motorboat_speedboat", "emergency_vehicle", "shout", "chainsaw", "oboe", "nose_blowing", "snake_hiss", "guitar_strum", "subway_metro", "fire", "wind_chime", "playing_hockey", "sneeze", "ringtone", "drum", "music", "frog_croak", "chime", "glockenspiel", "mosquito_buzz", "playing_squash", "bee_buzz", "finger_snapping", "crushing", "power_tool", "children_shouting", "hedge_trimmer", "water_tap_faucet", "waterfall", "knock", "toothbrush", "liquid_splashing", "zither", "humming", "didgeridoo", "sewing_machine", "speech", "bass_guitar", "wood_cracking", "harp", "sitar", "drum_kit", "harpsichord", "bell", "tuning_fork", "drawer_open_close", "theremin", "electric_shaver", "liquid_trickle_dribble", "cat_purr", "door_sliding", "laughter", "rail_transport", "electric_guitar", "boiling", "hiccup", "harmonica", "fireworks", "hi_hat", "wind", "crow_caw", "elk_bugle", "hammond_organ", "thump_thud", "drill", "blender", "guitar", "chewing", "tambourine", "rowboat_canoe_kayak", "horse_clip_clop", "traffic_noise", "typing", "playing_badminton", "disc_scratching", "mandolin", "burp", "train_horn", "boat_water_vehicle", "cowbell", "bird_vocalization", "pigeon_dove_coo", "writing", "flute", "truck", "clarinet", "goose_honk", "vacuum_cleaner", "race_car", "baby_laughter", "sigh", "snare_drum", "squeak", "tabla", "dog_howl", "vehicle_skidding", "yell", "artillery_fire", "tearing", "tick", "slap_smack", "steelpan", "cutlery_silverware", "zipper", "microwave_oven", "bird_chirp_tweet", "trumpet", "basketball_bounce", "car_horn", "police_siren", "toilet_flush", "person_shuffling", "civil_defense_siren", "bathtub_filling_washing", "bass_drum", "coin_dropping", "bicycle_bell", "liquid_dripping", "french_horn", "crumpling_crinkling", "rattle_instrument", "whispering", "gunshot_gunfire", "fire_engine_siren", "church_bell", "thunderstorm", "orchestra", "sheep_bleat", "gurgling", "train_wheels_squealing", "organ", "stream_burbling", "alarm_clock", "clapping", "horse_neigh", "ratchet_and_pawl", "vibraphone", "dog_bark", "typing_computer_keyboard", "violin_fiddle", "dog_bow_wow", "double_bass", "water_pump", "train_whistle", "train", "bird", "railroad_car", "ambulance_siren", "boom", "cello", "yodeling", "insect", "liquid_sloshing", "battle_cry", "eruption", "rope_skipping", "pig_oink", "choir_singing", "cat_meow", "dishes_pots_pans", "water", "glass_clink", "fly_buzz", "timpani", "underwater_bubbling", "scissors", "marimba_xylophone", "cymbal", "camera", "biting", "dog", "dog_growl", "ukulele", "turkey_gobble", "siren", "gong", "banjo", "brass_instrument", "screaming", "sailing", "door_slam", "steel_guitar_slide_guitar", "thunder", "mallet_percussion", "firecracker", "fowl", "singing_bowl", "booing", "hammer", "chuckle_chortle", "baby_crying", "person_walking", "slurp", "whistling", "hair_dryer", "synthesizer", "bird_flapping", "frog", "ocean", "liquid_squishing", "air_conditioner", "lawn_mower", "dog_whimper", "engine", "owl_hoot", "chicken", "bowed_string_instrument", "belly_laugh", "clock", "trombone", "saw", "whale_vocalization", "engine_idling", "aircraft", "door_bell"]

OBJECT365_CLASSES= ['Person', 'Sneakers', 'Chair', 'Other Shoes', 'Hat', 'Car', 'Lamp', 'Glasses', 'Bottle', 'Desk', 'Cup',
        'Street Lights', 'Cabinet/shelf', 'Handbag/Satchel', 'Bracelet', 'Plate', 'Picture/Frame', 'Helmet', 'Book',
        'Gloves', 'Storage box', 'Boat', 'Leather Shoes', 'Flower', 'Bench', 'Potted Plant', 'Bowl/Basin', 'Flag',
        'Pillow', 'Boots', 'Vase', 'Microphone', 'Necklace', 'Ring', 'SUV', 'Wine Glass', 'Belt', 'Monitor/TV',
        'Backpack', 'Umbrella', 'Traffic Light', 'Speaker', 'Watch', 'Tie', 'Trash bin Can', 'Slippers', 'Bicycle',
        'Stool', 'Barrel/bucket', 'Van', 'Couch', 'Sandals', 'Basket', 'Drum', 'Pen/Pencil', 'Bus', 'Wild Bird',
        'High Heels', 'Motorcycle', 'Guitar', 'Carpet', 'Cell Phone', 'Bread', 'Camera', 'Canned', 'Truck',
        'Traffic cone', 'Cymbal', 'Lifesaver', 'Towel', 'Stuffed Toy', 'Candle', 'Sailboat', 'Laptop', 'Awning',
        'Bed', 'Faucet', 'Tent', 'Horse', 'Mirror', 'Power outlet', 'Sink', 'Apple', 'Air Conditioner', 'Knife',
        'Hockey Stick', 'Paddle', 'Pickup Truck', 'Fork', 'Traffic Sign', 'Balloon', 'Tripod', 'Dog', 'Spoon', 'Clock',
        'Pot', 'Cow', 'Cake', 'Dinning Table', 'Sheep', 'Hanger', 'Blackboard/Whiteboard', 'Napkin', 'Other Fish',
        'Orange/Tangerine', 'Toiletry', 'Keyboard', 'Tomato', 'Lantern', 'Machinery Vehicle', 'Fan',
        'Green Vegetables', 'Banana', 'Baseball Glove', 'Airplane', 'Mouse', 'Train', 'Pumpkin', 'Soccer', 'Skiboard',
        'Luggage', 'Nightstand', 'Tea pot', 'Telephone', 'Trolley', 'Head Phone', 'Sports Car', 'Stop Sign',
        'Dessert', 'Scooter', 'Stroller', 'Crane', 'Remote', 'Refrigerator', 'Oven', 'Lemon', 'Duck', 'Baseball Bat',
        'Surveillance Camera', 'Cat', 'Jug', 'Broccoli', 'Piano', 'Pizza', 'Elephant', 'Skateboard', 'Surfboard',
        'Gun', 'Skating and Skiing shoes', 'Gas stove', 'Donut', 'Bow Tie', 'Carrot', 'Toilet', 'Kite', 'Strawberry',
        'Other Balls', 'Shovel', 'Pepper', 'Computer Box', 'Toilet Paper', 'Cleaning Products', 'Chopsticks',
        'Microwave', 'Pigeon', 'Baseball', 'Cutting/chopping Board', 'Coffee Table', 'Side Table', 'Scissors',
        'Marker', 'Pie', 'Ladder', 'Snowboard', 'Cookies', 'Radiator', 'Fire Hydrant', 'Basketball', 'Zebra', 'Grape',
        'Giraffe', 'Potato', 'Sausage', 'Tricycle', 'Violin', 'Egg', 'Fire Extinguisher', 'Candy', 'Fire Truck',
        'Billiards', 'Converter', 'Bathtub', 'Wheelchair', 'Golf Club', 'Briefcase', 'Cucumber', 'Cigar/Cigarette',
        'Paint Brush', 'Pear', 'Heavy Truck', 'Hamburger', 'Extractor', 'Extension Cord', 'Tong', 'Tennis Racket',
        'Folder', 'American Football', 'earphone', 'Mask', 'Kettle', 'Tennis', 'Ship', 'Swing', 'Coffee Machine',
        'Slide', 'Carriage', 'Onion', 'Green beans', 'Projector', 'Frisbee', 'Washing Machine/Drying Machine',
        'Chicken', 'Printer', 'Watermelon', 'Saxophone', 'Tissue', 'Toothbrush', 'Ice cream', 'Hot-air balloon',
        'Cello', 'French Fries', 'Scale', 'Trophy', 'Cabbage', 'Hot dog', 'Blender', 'Peach', 'Rice', 'Wallet/Purse',
        'Volleyball', 'Deer', 'Goose', 'Tape', 'Tablet', 'Cosmetics', 'Trumpet', 'Pineapple', 'Golf Ball',
        'Ambulance', 'Parking meter', 'Mango', 'Key', 'Hurdle', 'Fishing Rod', 'Medal', 'Flute', 'Brush', 'Penguin',
        'Megaphone', 'Corn', 'Lettuce', 'Garlic', 'Swan', 'Helicopter', 'Green Onion', 'Sandwich', 'Nuts',
        'Speed Limit Sign', 'Induction Cooker', 'Broom', 'Trombone', 'Plum', 'Rickshaw', 'Goldfish', 'Kiwi fruit',
        'Router/modem', 'Poker Card', 'Toaster', 'Shrimp', 'Sushi', 'Cheese', 'Notepaper', 'Cherry', 'Pliers', 'CD',
        'Pasta', 'Hammer', 'Cue', 'Avocado', 'Hamimelon', 'Flask', 'Mushroom', 'Screwdriver', 'Soap', 'Recorder',
        'Bear', 'Eggplant', 'Board Eraser', 'Coconut', 'Tape Measure/Ruler', 'Pig', 'Showerhead', 'Globe', 'Chips',
        'Steak', 'Crosswalk Sign', 'Stapler', 'Camel', 'Formula 1', 'Pomegranate', 'Dishwasher', 'Crab',
        'Hoverboard', 'Meat ball', 'Rice Cooker', 'Tuba', 'Calculator', 'Papaya', 'Antelope', 'Parrot', 'Seal',
        'Butterfly', 'Dumbbell', 'Donkey', 'Lion', 'Urinal', 'Dolphin', 'Electric Drill', 'Hair Dryer', 'Egg tart',
        'Jellyfish', 'Treadmill', 'Lighter', 'Grapefruit', 'Game board', 'Mop', 'Radish', 'Baozi', 'Target', 'French',
        'Spring Rolls', 'Monkey', 'Rabbit', 'Pencil Case', 'Yak', 'Red Cabbage', 'Binoculars', 'Asparagus', 'Barbell',
        'Scallop', 'Noddles', 'Comb', 'Dumpling', 'Oyster', 'Table Tennis paddle', 'Cosmetics Brush/Eyeliner Pencil',
        'Chainsaw', 'Eraser', 'Lobster', 'Durian', 'Okra', 'Lipstick', 'Cosmetics Mirror', 'Curling', 'Table Tennis']


CLASS_USER_RANKING = ['laptop', 'desk', 'table-merged', 'office', 'keyboard', 'mouse', 'cell phone', 'book', 'clock', 'chair', 'cabinet-merged', 'tv', 'remote', 'microwave', 'oven', 'refrigerator', 'sink', 'bottle', 'cup', 'scissors', 'banner', 'umbrella', 'tie', 'handbag', 'backpack', 'suitcase', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'wine glass', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'toaster', 'hair drier', 'toothbrush', 'blanket', 'bridge', 'cardboard', 'counter', 'curtain', 'door-stuff', 'floor-wood', 'flower', 'fruit', 'gravel', 'house', 'light', 'mirror-stuff', 'net', 'pillow', 'platform', 'playingfield', 'railroad', 'river', 'road', 'roof', 'sand', 'sea', 'shelf', 'snow', 'stairs', 'tent', 'towel', 'wall-brick', 'wall-stone', 'wall-tile', 'wall-wood', 'water-other', 'window-blind', 'window-other', 'tree-merged', 'fence-merged', 'ceiling-merged', 'sky-other-merged', 'floor-other-merged', 'pavement-merged', 'mountain-merged', 'grass-merged', 'dirt-merged', 'paper-merged', 'food-other-merged', 'building-other-merged', 'rock-merged', 'wall-other-merged', 'rug-merged', 'background']

COCO_CLASSES = [
    "hand", # it's person, changed for ASSETS 2025
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "bottle", # this is cell phone, changed for the purpose of ASSETS study
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "chocolate", # this is book, changed for the purpose of ASSETS study
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
    "banner",
    "blanket",
    "bridge",
    "cardboard",
    "counter",
    "curtain",
    "door-stuff",
    "floor-wood",
    "flower",
    "fruit",
    "gravel",
    "house",
    "light",
    "mirror-stuff",
    "net",
    "pillow",
    "platform",
    "playingfield",
    "railroad",
    "river",
    "road",
    "roof",
    "sand",
    "sea",
    "shelf",
    "snow",
    "stairs",
    "tent",
    "towel",
    "wall-brick",
    "wall-stone",
    "wall-tile",
    "wall-wood",
    "water-other",
    "window-blind",
    "window-other",
    "tree-merged",
    "fence-merged",
    "ceiling-merged",
    "sky-other-merged",
    "cabinet-merged",
    "table-merged",
    "floor-other-merged",
    "pavement-merged",
    "mountain-merged",
    "grass-merged",
    "dirt-merged",
    "paper-merged",
    "food-other-merged",
    "building-other-merged",
    "rock-merged",
    "wall-other-merged",
    "rug-merged",
    "background",
]

def sort_cls_with_preference(input_cls_list) -> list:
    return sorted(input_cls_list, key=lambda x: CLASS_USER_RANKING.index(x) if x in CLASS_USER_RANKING else len(CLASS_USER_RANKING))

if __name__ == '__main__':
    print(COCO_CLASSES[63])